[
    ../../pkgs/base.nix
    ../../pkgs/cloud.nix
    ../../pkgs/dev.nix
    ../../pkgs/games.nix
    ../../pkgs/internet.nix
    ../../pkgs/office.nix
    ../../pkgs/sage.nix
    ../../pkgs/school.nix
    ../../pkgs/utils.nix
]